config/routes.rb
Rails.application.routes.draw do
  root :to => 'pages#home'

  devise_for :users, controllers: { registrations: "registrations" }
  # don't want 404 on requesting users index, it breaks google crawlers
  # if user is signed in, login will actually redirect to pins
  get "/users", to: redirect("/login")

  devise_scope :user do
    get "/register" => "devise/registrations#new"
    get "/login" => "devise/sessions#new"
  end

  resources :users do
    resource :preferences
  end

  resources :comments, :only => [:new, :create, :destroy] do
    resources :flags, :only => [:create]
  end

  get 'contact' => 'contact#new'
  post 'contact' => 'contact#create'

  # FIXME duplicative
  resources :pin_images
  resources :pins do
    resources :pin_images
    resources :flags, :only => [:create]
  end

  resources :surgeons
  resources :procedures

  # TODO redundant?
  delete '/pins/:pin_id/flags/remove_flag' => 'flags#destroy', as: 'remove_pin_flag'
  delete '/comments/:comment_id/flags/remove_flag' => 'flags#destroy', as: 'remove_comment_flag'

  get 'by_user' => 'pins#by_user', :as => 'by'
  get 'pins' => 'pins#index'
  get 'queendom' => 'pins#admin'

  get 'about' => 'pages#about'
  get 'terms' => 'pages#terms'
  get 'privacy' => 'pages#privacy'
  get 'home' => 'pages#home'
  get 'newsfeed' => 'pages#newsfeed'

  get 'search_terms' => 'search#search_terms'
  get 'surgeons_only' => 'search#surgeons_only'

  # reroute for old bookmarks
  get '/members' => 'pages#home'
  get '/therapies' => 'pages#home'
  get '/therapists' => 'pages#home'
  get '/forum' => 'pages#home'
  get '/members/*other' => 'pages#home'
  get '/members/uploads/*other' => 'pages#home'

  # the logs get very noisy with backtraces unless we ignore missing images
  if Rails.env.development?
    get "/system/:url", to: proc { [410, {}, ['']] }, url: /.+/
  end
end

app/models/pin.rb
# "Pin" as a name is baggage from the original app,
# generic "pinning" of content.
# Now it is the primary submission model.
class Pin < ActiveRecord::Base
  include AASM
  include Searchable
  include Constants
  include PinsHelper
  include CommentsHelper
  include NotificationsHelper

  belongs_to :user
  belongs_to :surgeon
  belongs_to :procedure

  has_many :pin_images, dependent: :destroy

  attr_accessor :pin_image_ids

  acts_as_commentable
  acts_as_votable
  acts_as_taggable_on :complications

  # we have so few records we don't really need multiple shards
  settings index: { number_of_shards: 1 } do
    mapping do
      # no need to do full text search on this
      indexes :state, type: 'keyword'
      # keyword (exact term) doesn't make sense for these
      indexes :description, type: 'text', analyzer: 'english'
      indexes :details, type: 'text', analyzer: 'english'

      # we use the english analyzer, and do keywords as well as text
      # because then we can do significant terms aggregations
      # https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-lang-analyzer.html#english-analyzer
      indexes :complications do
        indexes :name, type: 'text', analyzer: 'english' do
          indexes :keyword, type: 'keyword'
        end
      end
      indexes :surgeon do
        indexes :pretty_name, type: 'text', analyzer: 'english' do
          indexes :keyword, type: 'keyword'
        end
      end
      indexes :procedure do
        indexes :name, type: 'text', analyzer: 'english' do
          indexes :keyword, type: 'keyword'
        end
        indexes :description, type: 'text', analyzer: 'english'
      end
      indexes :pin_images do
        indexes :caption, type: 'text', analyzer: 'english'
      end
    end
  end

  def as_indexed_json(options={})
    hash = self.as_json(
      only: [
        :id, :user_id, :procedure_id, :surgeon_id, :state, :username,
        :updated_at, :created_at, :description, :details,
        :satisfaction, :sensation, :revision, :cost
      ],
      include: {
        surgeon: { methods: [:pretty_name], only: [:pretty_name] },
        procedure: { only: [:name, :description] },
        pin_images: { only: [:caption] },
        complications: { only: [:name] }
      }
    )
    hash
  end

  validates :surgeon, presence: true
  validates :procedure, presence: true
  validates :user_id, presence: true
  validates :pin_images, presence: true

  aasm column: :state do
    state :pending, value: 'pending'
    state :published, value: 'published', initial: :published

    event :publish do
      transitions from: :pending, to: :published
    end

    event :review, :after => :admin_review do
      transitions from: :published, to: :pending
    end
  end

  def self.mtf
    where(['procedure_id in (?)', Constants::MTF_IDS])
  end

  def self.ftm
    where(['procedure_id in (?)', Constants::FTM_IDS])
  end

  def self.top
    where(['procedure_id in (?)', Constants::TOP_IDS])
  end

  def self.bottom
    where(['procedure_id in (?)', Constants::BOTTOM_IDS])
  end

  def self.need_category
    where(procedure_id: 911)
  end

  def self.recent
    published.order('updated_at desc')
  end

  def self.by_gender(gender_name)
    unless Gender.pluck(:name).include?(gender_name)
      raise Exception.new "Invalid Gender name"
    end
    joins('LEFT JOIN procedures on pins.procedure_id = procedures.id').where(procedures: { gender: gender_name })
  end

  def self.by_user_gender(user)
    by_gender(user.gender.name)
  end

  def self.by_user(user)
    includes(:pin_images, :user, :surgeon, :procedure).where(user_id: user)
  end

  def self.by_procedure(procedure)
    if procedure == [nil]
      where.not(procedure_id: procedure)
    else
      where(procedure_id: procedure)
    end
  end

  def self.by_surgeon(surgeon)
    if surgeon == [nil]
      where.not(surgeon_id: surgeon)
    else
      where(surgeon_id: surgeon)
    end
  end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  include SanitizeNames
  before_filter :authenticate_user!
  before_filter :validate_user, :only => [:edit, :update, :destroy]
  before_filter :get_pin, :except => [:index, :new, :create, :admin]
  respond_to :json

  # GET /pins
  # GET /pins.json
  def index
    @presenter = PinPresenter.new(pin_index_params)
    @comments = Comment.new_as_of(user_last_sign_in)
    respond_to do |format|
      format.html # index.html.erb
      format.js
    end
  end

  # GET /pins/1
  # GET /pins/1.json
  def show
    @comments = @pin.comments_asc
    @new_comment = Comment.build_from(@pin, current_user, "")

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @pin }
    end
  end

  # GET /pins/new
  # GET /pins/new.json
  def new
    @form = PinForm.new(current_user.pins.new)
    @form.prepopulate!
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @form.model }
    end
  end

  # GET /pins/1/edit
  def edit
    @form = PinForm.new(current_user.pins.find(params[:id]))
    @form.prepopulate!
  end

  # POST /pins
  # POST /pins.json
  def create
    @form = PinForm.new(current_user.pins.new)

    respond_to do |format|
      if @form.validate(pin_params)
        @form.save
        @pin = @form.model
        @pin.procedure.recalculate_avgs

        format.html { redirect_to @pin, notice: 'Pin was successfully created.' }
        format.json { render json: @pin, status: :created, location: @pin }
      else
        format.html { render action: 'new' }
        format.json { render json: @form.errors.full_messages, status: :unprocessable_entity }
      end
    end
  end

  # PUT /pins/1
  # PUT /pins/1.json
  def update
    @form = PinForm.new(current_user.pins.find(params[:id]))

    respond_to do |format|
      if @form.validate(pin_params)
        @form.save
        @pin = @form.model
        @pin.procedure.recalculate_avgs

        format.html { redirect_to @pin, notice: 'Pin was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @form.errors.full_messages, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pins/1
  # DELETE /pins/1.json
  def destroy
    @pin.destroy

    respond_to do |format|
      if Pin.find_by_id(@pin.id)
        flash[:error] = "Could not destroy #{@pin.id}!"
        format.json { render json: @pin.errors.full_messages, status: :unprocessable_entity }
      else
        flash[:notice] = "Destroyed #{@pin.id}"
        format.json { render json: { status: 'destroyed' }, status: :ok }
      end
    end
  end

  def admin
    @pins = Pin.where(state: 'pending').order("created_at desc")
    @comments = Comment.where(state: 'pending').order("created_at desc")
    @queue = { pins: @pins, comments: @comments }

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @queue }
    end
  end

  private
  def get_pin
    @pin = Pin.includes(comment_threads: [:children]).find(params[:id])
  end

  def id_or_attributes(attributes)
    return nil if attributes.nil?

    id = attributes.delete("id")

    if attributes["name"].present?
      attributes
    elsif !attributes.has_key?("name") and attributes.values.any?(&:present?)
      attributes
    else
      {"id" => id}
    end
  end

  def pin_params
    pin_images = params.delete(:pin_images)
    params[:pin][:pin_images] = pin_images.values unless pin_images.nil?
    params[:pin][:surgeon] = id_or_attributes(params[:pin].delete(:surgeon_attributes))
    params[:pin][:procedure] = id_or_attributes(params[:pin].delete(:procedure_attributes))
    params.require(:pin).permit!
    # FIXME: why was this commented out? should it be removed?
    # params.require(:pin).permit(:surgeon_id, :procedure_id, :cost, :revision, :details, :sensation, :satisfaction,
    # pin_images: [:photo, :caption])
  end

  def pin_index_params
    {
      query: query,
      scope: params[:scope],
      surgeon: params[:surgeon],
      procedure: params[:procedure],
      complication: params[:complication],
      user: params[:user],
      current_user: current_user,
      page: params[:page]
    }
  end

  def query
    sanitize_query(params[:query]) if params[:query]
  end

  def safe_mode
    current_user.preference.present? ? UserPolicy.new(current_user).safe_mode? : false
  end

  def user_last_sign_in
    User.find(current_user.id).try(:last_sign_in_at)
  end

  def validate_user
    pin = Pin.find(params[:id])

    if current_user == pin.user || current_user.admin
      return true
    else
      head :forbidden
    end
  end
end

app/helpers/pins_helper.rb
module PinsHelper
  PRONOUN_HASH = {
    1 => "he/him/his",
    2 => "she/her/hers",
    3 => "they/them/theirs",
    4 => "they/them/theirs"
  }

  # used to mimic the shape of a PinImage
  class FakeImage
    def url(_size)
      'http://placekitten.com/200/300'
    end
  end

  def uses_pronouns(author_gender)
    return "they/them/theirs" if author_gender.nil?
    PRONOUN_HASH[author_gender.id]
  end

  # FIXME: this could be a lot more robust, and reflect user preference rather than last
  def cover_image(safe_mode = false)
    kitty_url = FakeImage.new
    cover = images.try(:last) ? images.last : kitty_url
    image = safe_mode == true ? kitty_url : cover
    image
  end

  def images
    pin_images.collect { |pin| pin.photo }
  end

  def unknown_surgeon?
    if surgeon.present?
      surgeon.id == 911
    else
      update_attributes(surgeon_id: 911)
    end
  end

  def latest_comment_snippet
    try(:comment_threads).try(:last).try(:snippet)
  end
end

app/views/pins/_details.html.erb
<div class="control-group">
  <div class="header">
    <ul class="nav nav-pills pull-right">
      <li class="active">
      </li>
    </ul>
    <h3 class="text-muted">Your experience in depth:</h3>
  </div>
  <div class="controls">
  </div>
  <%= tinymce %>
  <%= f.text_area :details, :class => "tinymce", :rows => 15, :cols => 50 %>
</div>

app/views/pins/_errors.html.erb
<div id="error_explanation" class="submission_well<% if !form.errors.any? %> hide<% end %>">
  <% if form.errors.any? %>
    <h2><%= pluralize(form.errors.count, "error") %> prohibited this pin from being saved:</h2>
  <% end %>
  <ul>
    <% form.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>

app/views/pins/_latest_comment_snippet.erb
<div class="comment_box">
	<p>
		<%= fa_icon("comment", text: "#{pin.latest_comment_snippet}") %>
	</p>
</div>

app/views/pins/_new_and_edit_form.html.erb
<!-- New edit & new form -->
<%= form_for @form, html: {multipart: true, class: "form-inline", data: {"pin-id" => @form.try(:id)}} do |pin_form| %>
  <div class="row">
    <div class="top-block">
      <span class="h2"> <%= fa_icon "camera" %> Photos</span>
    </div>
    <div id="pin_images">
      <div class="submission_well">
        <%= render partial: 'pin_images/form', locals: {f: pin_form} %>
      </div>
    </div>
  </div>
  <%= render partial: 'errors', locals: {form: @form} %>
  <div class="row">
    <div class="top-block">
      <span class="h2"> <%= fa_icon "pencil" %> Details</span>
    </div>
  </div>
  <div class="row submission_well">
    <div class="col-md-6">
      <%= render partial: 'surgeon_and_procedure', locals: {f: pin_form} %>
      <%= render partial: 'more_options', locals: {f: pin_form} %>
    </div>
    <div class="col-md-6">
      <%= render partial: 'details', locals: {f: pin_form} %>
    </div>
  </div>
  <div class="row">
    <div class="submission_well col-md-12">
      <%= pin_form.submit "Submit Now", class: 'btn btn-success btn-block', id: "submit-all" %>
    </div>
  </div>
<% end %>
<%= render 'pins/surgeon_complete' %>

app/views/pins/_new_procedure.html.erb
<%= f.fields_for :procedure do |procedure_form| %>
<div class="well">
  <%= procedure_form.text_field :name, placeholder: "Name of procedure" %>
  <br>
  <label>Type
    <%= procedure_form.select :body_type, options_for_select([ "Top", "Bottom", "Face", "Other" ]) %>
  </label>
  <br>
  <label>Gender
    <%= procedure_form.select :gender, options_for_select([ "FTM", "MTF" ]) %>
  </label>
  <br>
  <%= procedure_form.link_to_remove "cancel" %>
</div>
<% end %>

app/views/pins/_new_surgeon.html.erb
<%= f.fields_for :surgeon do |surgeon_form| %>
<div class="well">
  <%= surgeon_form.text_field :last_name, placeholder: "Surgeon's last name" %>
  <%= surgeon_form.text_field :first_name, placeholder: "Surgeon's first name" %>
  <%= surgeon_form.text_field :url, placeholder: "Surgeon's URL" %>
  <br>
  <%= surgeon_form.link_to_remove "cancel" %>
</div>
<% end %>

app/views/pins/_photo.html.erb
<fieldset>
  <% if !f.object.new_record? %>
  <%= image_tag f.object.photo.url %>
  <% end %>

  <%= f.file_field :photo %>
  <%= f.label :caption, "Image Caption" %>
  <%= f.text_field :caption %>
  <%= delete_photo(f) %>
</fieldset>

app/views/pins/_pin.html.erb
<% if Rails.env.production? && rand(1..15) == 7 %>
  <% Rails.logger.debug "Serving ad with #{pin.id}" %>
  <div class="item" class="ad">
    <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
    <!-- test1 -->
    <ins class="adsbygoogle"
         style="display:block"
         data-ad-client="ca-pub-3154444439610781"
         data-ad-slot="3311943876"
         data-ad-format="auto"
         data-full-width-responsive="true"></ins>
    <script>
      (adsbygoogle = window.adsbygoogle || []).push({});
    </script>
  </div>
<% end %>
<!-- end ad snippet  -->
<% if pin.published? %>
<div class="item" data-pin-id="<%= pin.id %>" itemscope>
  <div class="panel panel-default">
    <div class="panel-body">
    <%= render partial: "latest_comment_snippet", locals: { pin: pin } if @comments.map(&:commentable_id).include?(pin.id) %>
    <% cache([pin, @safe_mode]) do %>
      <div class="image" itemprop="image">
        <%= link_to (image_tag pin.cover_image(@safe_mode).url(:medium)), pin %>
      </div>
      <p class="description" itemprop="description">
        <%= pin.try(:procedure).try(:name) %> by <strong><%= pin.unknown_surgeon? ? 'unknown' : 'Dr. ' + pin.surgeon.to_s %></strong>
      </p>
    <% end %>
    <!-- end cache fragment  -->
    </div>
    <!-- panel body end -->
    <div class="panel-footer">
      <div class="actions">
        <label class="label-with-popover" data-placement="right" data-content="Flags from 3 different users will remove content pending review by a moderator." data-title="Flag this content." data-trigger="hover">
          <%= link_to(fa_icon("flag"), pin_flags_path(pin), method: :post, remote: true, "data-pin-id" => pin.id, class: "flag-pin") + " | " unless current_user == pin.user %>
        </label>
      <% if current_user == pin.user || current_user.admin? %>
        <%= link_to fa_icon("pencil-square-o"), edit_pin_path(pin) %>
        | <%= link_to fa_icon("trash-o"), pin, method: :delete, data: { confirm: 'Are you sure?' } %>
      <% if pin.pending? %>
        | <%= link_to 'Remove Flag', remove_pin_flag_path(pin), remote: true %>
      <% end %>
      <!-- end if pin pending -->
      <% end %>
      <!-- end if user can edit -->
        updated <%= distance_of_time_in_words(Time.now, pin.updated_at) %> ago
      </div>
      <!-- end footer actions -->
    </div>
    <!-- end panel footer -->
  </div>
</div>
<% end %>

app/views/pins/_surgeon_and_procedure.html.erb
<div class="row">
  <% f.hidden_field :id %>
  <div class="form-group col-md-6">
    <label class="control-label">Surgeon</label>
    <div id="surgeon_form" class="controls">
      <%= f.fields_for :surgeon do |surgeon_form| %>
        <%= surgeon_form.select :id, options_from_collection_for_select(Surgeon.order('last_name ASC'), 'id', 'to_s', surgeon_form.object.id) %>

        <a id="add_new_surgeon" href="#" class="add-button"><%= fa_icon("plus-circle") %></a>
        <%= render partial: 'surgeons/surgeon', locals: {surgeon_form: surgeon_form} %>
      <% end %>
    </div>
  </div>
  <div class="form-group col-md-6">
    <label class="control-label">Procedure</label>
    <div id="procedure_form" class="controls">
      <%= f.fields_for :procedure do |procedure_form| %>
        <%= procedure_form.select :id, options_from_collection_for_select(Procedure.order('name ASC'), 'id', 'to_s', procedure_form.object.id) %>

        <a id="add_new_procedure" href="#" class="add-button"><%= fa_icon("plus-circle") %></a>
        <%= render partial: 'procedures/new_procedure', locals: {procedure_form: procedure_form} %>
      <% end %>
    </div>
  </div>
</div>

app/views/pins/_surgeon_complete.html.erb
<!--TODO why is this in an erb file? -->
<script>
  $(document).ready(function(){
    $(function() {
      var realTime = '<%= surgeons_only_url %>'
      $( "#pin_surgeon" ).autocomplete({
        source: realTime,
        minLength: 2
      });
      $('ul.ui-autocomplete.ui-menu').css('top', '35px');
    });
  });
</script>

app/views/pins/by_user.html.erb
<h2><%= title 'Submissions By User Results' %></h2>
<div id="controls" class="row">
  <div class="page_container" class="col-md-6" style="float:left;">
    <%= will_paginate @pins unless @pins.nil? %>
  </div>
</div>
<br clear="both" />
<div id="pins" class="js-masonry" data-masonry-options='{ "columnWidth": 200, "itemSelector": ".box" }'>
  <div id="pin_container">
    <%= render @pins %>
  </div>
</div>
<br>
<br clear="both" />
<div class="page_container" class="col-md-6">
  <%= will_paginate @pins unless @pins.nil? %>
</div>

app/views/pins/edit.html.erb
<% title 'Editing Submission' %>
<%= render 'new_and_edit_form' %>

app/views/pins/new.html.erb
<% title 'New Submission' %>

<%= render 'new_and_edit_form' %>

app/views/pins/show.html.erb
<% title 'Submission #' + @pin.id.to_s %>
<% cache(["pin_show", @pin, @pin.pin_images.map(&:id), @pin.pin_images.maximum(:updated_at)]) do %>
  <div class="row">
    <div class="col-md-6">
      <div class="well">
        <% for pinimage in @pin.pin_images.reject {|p| p.photo_file_size.nil?} do %>
          <div class="thumbnail">
            <%= image_tag pinimage.photo %>
            <div class="caption">
              <%= pinimage.caption.to_s %>
            </div>
          </div>
        <% end %>
        <br>
        <%= link_to fa_icon("arrow-left"), pins_path %>
        <% if current_user == @pin.user || current_user.admin == true %>
          | <%= link_to fa_icon("pencil-square-o"), edit_pin_path(@pin) %>
      <% end %>
    </div>
  </div>
  <div class="col-md-6">
    <dl class="dl-horizontal">
      <dt>
        <%= fa_icon "user-md" %> Surgeon
      </dt>
      <dd>
        <%= link_to @pin.unknown_surgeon? ? 'unknown' : 'Dr. ' + @pin.surgeon.to_s, surgeon_path(@pin.surgeon) %>
      </dd>
      <dt>
        <%= fa_icon "plus-square" %> Procedure
      </dt>
      <dd>
        <%= link_to @pin.procedure.name, pins_path({procedure: [@pin.procedure.id]}) %>
      </dd>
      <dt>
        <%= fa_icon "usd" %> Cost
      </dt>
      <dd>
        <%= number_with_delimiter(@pin.cost) %>
      </dd>
      <% if @pin.complications.present? %>
        <dt>
          <%= fa_icon "medkit" %> Complications
        </dt>
        <dd>
          <% @pin.complications.each do |complication| %>
            <%= link_to complication, pins_path(complication: complication.name) %>
          <% end %>
        </dd>
      <% end %>
      <% if @pin.revision %>
        <dt>
          <%= fa_icon "exclamation-circle" %> Wants revision
        </dt>
        <dd></dd>
      <% end %>
      <% if @pin.sensation.present? %>
        <dt>
          Post-op Sensation</dt>
        <dd>
          <%= number_field(:pin, :sensation, {class: "rating", disabled: "disabled", data: {size: 'xs'}}) %>
        </dd>
        <br>
      <% end %>
      <% if @pin.satisfaction.present? %>
        <dt>Post-op Satisfaction</dt>
        <dd>
          <%= number_field(:pin, :satisfaction, {class: "rating", disabled: "disabled", data: {size: 'xs'}}) %>
        </dd>
        <br clear="both">
      <% end %>
      <% if @pin.user.present? %>
        <dt>Submitter</dt>
        <dd><strong><%= link_to @pin.user.username.presence || @pin.user.id, pins_path(user: @pin.user) %></strong></dd>
      <% end %>
    </dl>
    <% if @pin.details.present? %>
      <div id="details">
        <%= fa_icon "quote-left" %>
        <%= @pin.details.try(:html_safe) %>
      </div>
    <% end %>
  </div>
  <br clear="both" />
<% end %>
<div id="comments-container">
  <h4><%= fa_icon("comments-o") %> discussion</h4>
  <%= render :partial => 'comments/comment', :collection => @comments, :as => :comment %>
    <h5>Please respect pronouns when writing to the submission author. The author's preferred pronouns are: <%= uses_pronouns(@pin.user.try(:gender)) %>.</h5>
  <%= link_to "<h5>#{fa_icon("comments-o")} add thread</h5>".html_safe, new_comment_path(commentable_id: @pin.id, commentable_type: "Pin"), remote: true %>
  <div id="commentable" class="reply-target">
  </div>
</div>