config/routes.rb
Rails.application.routes.draw do
  root :to => 'pages#home'

  devise_for :users, controllers: { registrations: "registrations" }
  # don't want 404 on requesting users index, it breaks google crawlers
  # if user is signed in, login will actually redirect to pins
  get "/users", to: redirect("/login")

  devise_scope :user do
    get "/register" => "devise/registrations#new"
    get "/login" => "devise/sessions#new"
  end

  resources :users do
    resource :preferences
  end

  resources :comments, :only => [:new, :create, :destroy] do
    resources :flags, :only => [:create]
  end

  get 'contact' => 'contact#new'
  post 'contact' => 'contact#create'

  # FIXME duplicative
  resources :pin_images
  resources :pins do
    resources :pin_images
    resources :flags, :only => [:create]
  end

  resources :surgeons
  resources :procedures

  # TODO redundant?
  delete '/pins/:pin_id/flags/remove_flag' => 'flags#destroy', as: 'remove_pin_flag'
  delete '/comments/:comment_id/flags/remove_flag' => 'flags#destroy', as: 'remove_comment_flag'

  get 'by_user' => 'pins#by_user', :as => 'by'
  get 'pins' => 'pins#index'
  get 'queendom' => 'pins#admin'

  get 'about' => 'pages#about'
  get 'terms' => 'pages#terms'
  get 'privacy' => 'pages#privacy'
  get 'home' => 'pages#home'
  get 'newsfeed' => 'pages#newsfeed'

  get 'search_terms' => 'search#search_terms'
  get 'surgeons_only' => 'search#surgeons_only'

  # reroute for old bookmarks
  get '/members' => 'pages#home'
  get '/therapies' => 'pages#home'
  get '/therapists' => 'pages#home'
  get '/forum' => 'pages#home'
  get '/members/*other' => 'pages#home'
  get '/members/uploads/*other' => 'pages#home'

  # the logs get very noisy with backtraces unless we ignore missing images
  if Rails.env.development?
    get "/system/:url", to: proc { [410, {}, ['']] }, url: /.+/
  end
end

app/models/comment.rb
# https://github.com/elight/acts_as_commentable_with_threading/blob/a579b92b497cbb2b5b5e8be78b760cf1c652dfa3/lib/generators/acts_as_commentable_upgrade_migration/comment.rb
class Comment < ActiveRecord::Base
  include AASM
  include NotificationsHelper
  validates :body, presence: true
  validates :user, presence: true

  # votes on comments are just flags
  # flags determine whether something needs to be reviewed
  acts_as_votable
  alias_method :flags, :votes

  # this is what turns on threading, otherwise we'd be stuck with
  # recursive eager loading
  acts_as_nested_set scope: [:commentable_id, :commentable_type]
  belongs_to :commentable, polymorphic: true
  belongs_to :user

  aasm column: :state do
    state :pending, value: 'pending'
    state :published, value: 'published', initial: :published

    event :publish do
      transitions from: :pending, to: :published
    end

    event :review, :after => :admin_review do
      transitions from: :published, to: :pending
    end
  end

  def self.new_as_of(last_login_time)
    where("created_at > ? and state = 'published'", last_login_time)
  end

  def self.find_comments_by_user(user)
    where(user_id: user.id).order('created_at DESC')
  end

  def self.find_comments_for_commentable(commentable_str, commentable_id)
    where(commentable_type: commentable_str.to_s,
          commentable_id: commentable_id).
          order('created_at DESC')
  end

  def self.find_commentable(commentable_str, commentable_id)
    commentable_str.constantize.find(commentable_id)
  end

  def self.build_from(obj, user_id, comment)
    new \
      commentable: obj,
      body: comment,
      user_id: user_id.id
  end

  def snippet
    if body.include?(' ')
      body.split(' ').first(5).join(' ')
    else
      body[0..49]
    end
  end

  # helper method to check if a comment has children
  def has_children?
    children.size > 0
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  respond_to :js

  def new
    @commentable = commentable
    @parent_id = parent_id # as in, parent comment, may be nil
    @new_comment = Comment.build_from(@commentable, current_user, "")
  end

  def create
    service = CommentService.new(
      commented_on,
      current_user,
      comment_params[:body],
      parent_id
    )
    service.create

    @comment = service.comment
    #TODO clean this up
    if @comment.commentable_type == "Pin"
      @pin = @comment.commentable_type.constantize.find(@comment.commentable_id)
    else
      @procedure = @comment.commentable_type.constantize.find(@comment.commentable_id)
    end

    if @comment.errors.present?
      render :json => @comment.errors, :status => :unprocessable_entity
    else
      render :partial => "comments/comment", :locals => { :comment => @comment }, :layout => false, :status => :created
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    if @comment.destroy
      render :json => {'status': 'destroyed'}, :status => :ok
    else
      render :json => @comment.errors, :status => :unprocessable_entity
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:commentable_id, :commentable_type, :parent_id, :body)
  end

  def commentable
    params[:commentable_type].constantize.find(params[:commentable_id])
  end

  def parent_id
    begin
      comment_params[:parent_id]
    rescue
      params[:parent_id]
    end
  end

  def commented_on
    comment_params[:commentable_type].constantize.find(comment_params[:commentable_id])
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
  def comments_asc
    timestamp = comment_threads.order('updated_at DESC').first.try(:updated_at)
    return [] if timestamp.nil?

    Rails.cache.fetch("#{timestamp.to_i}-#{comment_threads.pluck(:id).join('-')}") do
      comment_threads.where(parent_id: nil).
        includes(:user).
        order('updated_at asc')
    end
  end
end

app/views/comments/_comment.html.erb
<% if comment.published? %>
  <% cache(comment) do %>
    <div class="comment" id="comment-<%=comment.id %>" data-comment-id="<%= comment.id %>">
      <div class="panel panel-default">
        <div class="panel-body">
          <%= comment.body %>
        </div>
        <div class="panel-footer">
          <small>
            by <strong>
              <%= link_to comment.user.try(:username) || comment.user.try(:id), pins_path(user: comment.user) %>
            </strong> |
            <%= comment.updated_at.strftime('%b %d, %Y at %I:%M %p') %> |
            <% commentable = @pin ? @pin : @procedure %>
            <%= link_to "#{fa_icon("comments")} reply".html_safe, new_comment_path(commentable_id: commentable.try(:id), commentable_type: commentable.try(:class), parent_id: comment.id), remote: true %>
            <%= " | " unless current_user == comment.user %>
            <%= link_to(fa_icon("flag"), comment_flags_path(comment), :method => :post, remote: true, class: "flag-comment", "data-comment-id" => comment.id) unless current_user == comment.user %>
          </small>
          <% if comment.user_id == current_user.id || current_user.admin? %>
            <%= link_to "×", comment_path(comment), :method => :delete, :remote => true, data: {confirm: "Are you sure you want to remove this comment?"}, :disable_with => "×", :class => 'close' %>
          <% end %>
          <% cache(comment.children) do %>
            <% if comment.children.present? %>
              <hr class="thread">
              <%= render :partial => 'comments/comment', :collection => comment.children, :as => :comment %>
            <% end %>
          <% end %>
          <div class="reply-target">
          </div>
        </div>
      </div>
    </div>
  <% end %>
<% end %>

app/views/comments/_form.html.erb
<div id="create_comment_form">
  <%= simple_form_for @new_comment, :remote => true do |f| %>
    <%= f.error_notification %>
    <%= f.input :body, :input_html => {:style => 'width: 99%', :rows => "4"}, :label => false, :placeholder => "Comments that violate our Terms of Service are grounds for immediate and permanent deactivation." %>
    <%= f.hidden_field :parent_id, :value => @parent_id %>
    <%= f.hidden_field :commentable_id, :value => @new_comment.commentable_id %>
    <%= f.hidden_field :commentable_type, :value => @new_comment.commentable_type %>
    <%= f.submit "Submit", class: "btn btn-primary", :disable_with => "Submitting..." %>
  <% end %>
</div>

<br clear="both">

app/views/comments/new.js.erb
$("<%= @parent_id ? "#comment-#{@parent_id} " : '#commentable' %>.reply-target").last().append(
  "<%= escape_javascript(render :partial => 'comments/form', :locals => { :comment => @new_comment }) %>"
).focus();