config/routes.rb
Rails.application.routes.draw do
  root :to => 'pages#home'

  devise_for :users, controllers: { registrations: "registrations" }
  # don't want 404 on requesting users index, it breaks google crawlers
  # if user is signed in, login will actually redirect to pins
  get "/users", to: redirect("/login")

  devise_scope :user do
    get "/register" => "devise/registrations#new"
    get "/login" => "devise/sessions#new"
  end

  resources :users do
    resource :preferences
  end

  resources :comments, :only => [:new, :create, :destroy] do
    resources :flags, :only => [:create]
  end

  get 'contact' => 'contact#new'
  post 'contact' => 'contact#create'

  # FIXME duplicative
  resources :pin_images
  resources :pins do
    resources :pin_images
    resources :flags, :only => [:create]
  end

  resources :surgeons
  resources :procedures

  # TODO redundant?
  delete '/pins/:pin_id/flags/remove_flag' => 'flags#destroy', as: 'remove_pin_flag'
  delete '/comments/:comment_id/flags/remove_flag' => 'flags#destroy', as: 'remove_comment_flag'

  get 'by_user' => 'pins#by_user', :as => 'by'
  get 'pins' => 'pins#index'
  get 'queendom' => 'pins#admin'

  get 'about' => 'pages#about'
  get 'terms' => 'pages#terms'
  get 'privacy' => 'pages#privacy'
  get 'home' => 'pages#home'
  get 'newsfeed' => 'pages#newsfeed'

  get 'search_terms' => 'search#search_terms'
  get 'surgeons_only' => 'search#surgeons_only'

  # reroute for old bookmarks
  get '/members' => 'pages#home'
  get '/therapies' => 'pages#home'
  get '/therapists' => 'pages#home'
  get '/forum' => 'pages#home'
  get '/members/*other' => 'pages#home'
  get '/members/uploads/*other' => 'pages#home'

  # the logs get very noisy with backtraces unless we ignore missing images
  if Rails.env.development?
    get "/system/:url", to: proc { [410, {}, ['']] }, url: /.+/
  end
end

app/models/procedure.rb
class Procedure < ActiveRecord::Base
  include Stats
  include CommentsHelper
  extend FriendlyId
  friendly_id :name, use: :slugged

  has_many :pins
  has_many :skills
  has_many :surgeons, through: :skills

  acts_as_commentable

  # attr_accessible :name, :body_type, :gender, :avg_sensation, :avg_satisfaction

  # all procedures are stored lowercase
  before_save { self.name.downcase! }

  # but when we validate the incoming record we compare case insensitive
  # because we haven't downcased incoming string yet
  validates :name, uniqueness: { case_sensitive: false }
  validates :name, presence: true

  def to_s
    name
  end

  def self.names
    self.pluck(:name).sort
  end
end

app/controllers/procedures_controller.rb
class ProceduresController < ApplicationController
  def index
    @procedures = Procedure.all.order(:name)
    @pins_per_procedure = Procedure.joins(:pins).group("pins.procedure_id").count
    @comments_per_procedure = Procedure.joins(:comment_threads).group("comments.commentable_id").count
  end

  def show
    @procedure = Procedure.includes(comment_threads: [:children]).friendly.find(params[:id])
    # procedure pages are public, but comments should be private
    if current_user
      @comments = @procedure.comments_asc
      @new_comment = Comment.build_from(@procedure, current_user, "")
    end
  end

  def new
    @procedure = Procedure.new

    respond_to do |format|
      format.js
    end
  end

  def create
    @procedure = Procedure.new(procedure_params)

    if @procedure.save
      respond_to do |format|
        format.js  { @procedures = Procedure.order('name ASC'); @procedure }
      end
    end
  end

  private
  def procedure_params
    params.require(:procedure).permit(:name, :body_type, :gender)
  end
end

app/views/procedures/_new_procedure.html.erb
<div id="procedure_container" class="add-form hide">
  <div class="panel panel-default">
    <div class="panel-heading">
      <%= link_to fa_icon("times"), '#', class: 'cancel pull-right' %>
      <h3 class="panel-title">Add a new procedure</h3>
    </div>
    <div class="panel-body">
      <div class="input-group padded_nicely">
        <%= procedure_form.text_field :name, placeholder: "Name of procedure" %>
      </div>
      <div class="input-group padded_nicely">
        <%= procedure_form.select :body_type, options_for_select([ "Top", "Bottom", "Face", "Other" ]) %>
      </div>
      <div class="input-group padded_nicely">
        <%= procedure_form.select :gender, options_for_select([ "FTM", "MTF" ]) %>
      </div>
      <div class="input-group padded_nicely">
        <%= procedure_form.text_field :description, placeholder: "Describe this procedure" %>
      </div>
    </div>
  </div>
</div>

app/views/procedures/_procedure.html.erb
<tr itemscope itemtype="https://schema.org/MedicalProcedure">
  <td><%= link_to procedure.name.titleize, procedure_path(procedure) %></td>
  <% if user_signed_in? %>
  <td><%= link_to @pins_per_procedure[procedure.id] || 0, pins_path(procedure: procedure.id) %></td>
<% else %>
  <td><%= link_to "Register to see more", register_path  %></td>
  <% end %>
  <td><%= procedure.avg_satisfaction %></td>
  <td><%= procedure.avg_sensation %></td>
  <td><%= @comments_per_procedure[procedure.id] || 0 %></td>
</tr>

app/views/procedures/create.js.erb
$("#pin_procedure_id").html("<%= escape_javascript(select_tag :procedure_id, options_from_collection_for_select(@procedures, 'id', 'to_s', @procedure)) %>");
$('#pin_procedure_id option[value="<%= escape_javascript(@procedure.id.to_s) %>"]').attr('selected','selected');
$("#pin_procedure_id").trigger("chosen:updated");

app/views/procedures/index.html.erb
<%= render partial: 'ads/test1' %>
<% title "Procedures" %>
<div id="procedures" style="background-color:#ffffff">
  <table class="table table-hover table-bordered" bgcolor="#ffffcc">
    <th>Name</th>
    <th>Submissions</th>
    <th>Average Satisfaction</th>
    <th>Average Sensation</th>
    <th>Discussion Threads</th>
    <%= render @procedures %>
  </table>
</div>

app/views/procedures/new.js.erb
// adds the actual form
$("<%= escape_javascript(render @procedure) %>").appendTo("#procedure_form");

// sets up the behavior around submitting it and updating the select box
$("#new_procedure_submit").click(function() {
    var formElement = document.getElementById("new_procedure");
    formData = new FormData(formElement);

    return $.ajax({
        type: "POST",
        url: "/procedures",
        data: formData,
        processData: false,  // tell jQuery not to process the data
        contentType: false,   // tell jQuery not to set contentType
        success: function(data) {
            // see create.js.erb file for the rendering of the new collection
            $("#pin_procedure_id").trigger("chosen:updated");
            $("#procedure_container").hide("slow", function() {
                $("#procedure_container").remove();
            });
            return false;
        },
        error: function(data) {
            console.log('error:' + data)
            return false;
        }
    });
});

$('#procedure_form .cancel').click(function(){
    $("#procedure_container").hide("slow", function() {
        $("#procedure_container").remove();
    });
});

app/views/procedures/show.html.erb
<% title @procedure.to_s  %>
<% cache(@procedure) do %>
  <div class="panel panel-default" itemscope itemtype="https://schema.org/MedicalProcedure">
    <div class="panel-heading">
      <h2><%= @procedure.name %></h2>
      <%= link_to "See all submissions", pins_path(procedure: @procedure.id) %>
    </div>
    <% if @procedure.body_type %>
      <div class="panel-body" itemprop="bodyLocation">
        <i>This procedure is classified as a "<%= @procedure.body_type %>" procedure.</i>
      </div>
    <% end %>
    <% if @procedure.description %>
      <div class="panel-body" itemprop="description" itemprop="howPerformed">
        <%= @procedure.description %>
      </div>
    <% end %>
    <!-- List group -->
    <ul class="list-group">
      <li class="list-group-item">
        Average sensation: <%= @procedure.avg_sensation %>
      </li>
      <li class="list-group-item">
        Average satisfaction: <%= @procedure.avg_satisfaction %>
      </li>
    </ul>
  </div>
<% end %>

<% if current_user %>
  <h4><%= fa_icon("comments-o") %> discussion</h4>
  <div id="comments-container">
    <%= render :partial => 'comments/comment', :collection => @comments, :as => :comment %>
    <%= link_to "<h5>#{fa_icon("comment-o")} add thread</h5>".html_safe, new_comment_path(commentable_id: @procedure.id, commentable_type: "Procedure"), remote: true %>
    <div id="commentable" class="reply-target">
    </div>
  </div>
<% end %>