config/routes.rb
Rails.application.routes.draw do
  root :to => 'pages#home'

  devise_for :users, controllers: { registrations: "registrations" }
  # don't want 404 on requesting users index, it breaks google crawlers
  # if user is signed in, login will actually redirect to pins
  get "/users", to: redirect("/login")

  devise_scope :user do
    get "/register" => "devise/registrations#new"
    get "/login" => "devise/sessions#new"
  end

  resources :users do
    resource :preferences
  end

  resources :comments, :only => [:new, :create, :destroy] do
    resources :flags, :only => [:create]
  end

  get 'contact' => 'contact#new'
  post 'contact' => 'contact#create'

  # FIXME duplicative
  resources :pin_images
  resources :pins do
    resources :pin_images
    resources :flags, :only => [:create]
  end

  resources :surgeons
  resources :procedures

  # TODO redundant?
  delete '/pins/:pin_id/flags/remove_flag' => 'flags#destroy', as: 'remove_pin_flag'
  delete '/comments/:comment_id/flags/remove_flag' => 'flags#destroy', as: 'remove_comment_flag'

  get 'by_user' => 'pins#by_user', :as => 'by'
  get 'pins' => 'pins#index'
  get 'queendom' => 'pins#admin'

  get 'about' => 'pages#about'
  get 'terms' => 'pages#terms'
  get 'privacy' => 'pages#privacy'
  get 'home' => 'pages#home'
  get 'newsfeed' => 'pages#newsfeed'

  get 'search_terms' => 'search#search_terms'
  get 'surgeons_only' => 'search#surgeons_only'

  # reroute for old bookmarks
  get '/members' => 'pages#home'
  get '/therapies' => 'pages#home'
  get '/therapists' => 'pages#home'
  get '/forum' => 'pages#home'
  get '/members/*other' => 'pages#home'
  get '/members/uploads/*other' => 'pages#home'

  # the logs get very noisy with backtraces unless we ignore missing images
  if Rails.env.development?
    get "/system/:url", to: proc { [410, {}, ['']] }, url: /.+/
  end
end

app/views/layouts/_account_menu.html.erb
<ul class="nav navbar-nav">
  <li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= I18n.t(".header.account")%> <span class="caret"></span></a>
    <ul class="dropdown-menu" role="menu">
      <% if user_signed_in? %>
        <li><%= link_to I18n.t(".account_menu.my_account"),  edit_user_registration_path %></li>
        <li><%= link_to I18n.t(".account_menu.logout"),  destroy_user_session_path, method: :delete %></li>
      <% else %>
        <li><%= link_to I18n.t(".account_menu.login"),  new_user_session_path %></li>
        <li><%= link_to I18n.t(".account_menu.register"), register_path %></li>
      <% end %>
    </ul>
  </li>
</ul>

app/views/layouts/_footer.html.erb
<div class="footer navbar-fixed-bottom submission_well">
  <% cache("#{I18n.locale}_#{Date.today.year}") do %>
    <small> &nbsp;
      <%= link_to I18n.t('.footer.about'),  about_path %> |
      <%= link_to I18n.t('.footer.tos'), terms_path %> |
      <%= link_to I18n.t('.footer.pp'), privacy_path %> |
      <%= fa_icon "facebook", class: 'yellow' %> <a href="https://www.facebook.com/transbucket">Transbucket</a> <%= fa_icon "twitter", class: 'yellow' %> <a href="https://twitter.com/TransBucket">@TransBucket</a> |
      Join the <a href="https://discord.gg/Z72ec87K">Transbucket.com Discord</a>!
    </small>
  <% end %>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to image_tag("small_logo.png", :size => "16x16", :alt => "Index"), root_path, :class => "navbar-brand" %>
      <% unless user_signed_in? %>
        <a class="navbar-brand" href="<%= root_path %>">Transbucket.com</a>
      <% end %>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li>
          <%= link_to I18n.t('.header.news'),  newsfeed_path %>
        </li>
        <li>
          <%= link_to I18n.t('.header.procedures'),  procedures_path %>
        </li>
        <li>
          <%= link_to I18n.t('.header.surgeons'),  surgeons_path %>
        </li>
        <% if user_signed_in? %>
          <%= render partial: 'layouts/logged_in' %>
        <% end %>
        <%= render partial: 'layouts/account_menu' %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_logged_in.html.erb
<% if current_user.admin? %>
  <li class="bg-danger">
    <%= link_to 'ModQueue', queendom_path %>
  </li>
<% end %>
<li>
  <%= link_to I18n.t(".header.submissions"), pins_path %>
</li>
<% if current_page?(pins_path) %>
  <li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
      <%= I18n.t(".header.filter") %> <%= fa_icon "filter", { class: 'yellow' } %>
    </a>
    <ul class="dropdown-menu" role="menu">
      <li>
        <%= render partial: 'pins/filter_controls' %>
      </li>
    </ul>
  </li>
<% end %>
<% unless current_user.gender.cis? %>
  <li>
    <%= link_to "#{I18n.t(".header.add")} #{fa_icon('plus-circle yellow')}".html_safe, new_pin_path %>
  </li>
<% end %>
</ul>
<%= render partial: 'layouts/search' %>

app/views/layouts/_search.html.erb
<% cache(I18n.locale) do %>
  <%= javascript_include_tag 'search' %>
  <%= form_tag pins_path, :class => 'navbar-form navbar-right', :method => :get do %>
    <div class="input-group">
      <%= text_field_tag 'query', value = nil, :class => 'span2 search-query form-control', :placeholder => I18n.t(".header.search") %>
      <%#= autocomplete_field_tag 'pin', '', autocomplete_procedure_pin_index_path, :size => 75 %>
      <div class="input-group-btn">
        <%= button_tag '', :class => 'btn btn-default glyphicon glyphicon-search yellow' %>
      </div>
    </div>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= display_meta_tags :reverse => true, :site => 'Transbucket.com' %>
    <% if Rails.env.production? %>
      <!-- Global site tag (gtag.js) - Google Analytics -->
      <script async src="https://www.googletagmanager.com/gtag/js?id=UA-40933997-1"></script>
      <script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());
        gtag('config', 'UA-40933997-1');
      </script>
      <script data-ad-client="ca-pub-3154444439610781" async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
    <% end %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% if user_signed_in? %>
        <div id="flash-message">
          <% flash.each do |name, msg| %>
            <%= content_tag(:div, msg, class: "alert", id: "flash-#{name}") %>
          <% end %>
        </div>
      <% end %>
      <%= yield %>
    </div>
    <%= any_login_here if Rails.env.development? %>
    <%= render 'layouts/footer' %>
  </body>
</html>